import { minify as minifyJS } from 'npm:terser'
import { minify as minifyHTML } from 'npm:html-minifier-next'

const toKB = n => `${(n / 1000).toFixed(2)}kb`
const minifyOpts = {
  caseSensitive: false,
  collapseBooleanAttributes: true,
  collapseInlineTagWhitespace: true,
  collapseWhitespace: true,
  conservativeCollapse: true,
  decodeEntities: true,
  html5: true,
  includeAutoGeneratedTags: true,
  keepClosingSlash: false,
  maxLineLength: false,
  minifyCSS: true,
  minifyJS: async js => (await minifyJS(js)).code,
  minifyURLs: true,
  preserveLineBreaks: false,
  preventAttributesEscaping: true,
  processConditionalComments: true,
  removeAttributeQuotes: true,
  removeComments: true,
  removeEmptyAttributes: true,
  removeEmptyElements: false,
  removeOptionalTags: true,
  removeRedundantAttributes: true,
  removeScriptTypeAttributes: true,
  removeStyleLinkTypeAttributes: true,
  removeTagWhitespace: true,
  sortAttributes: true,
  sortClassName: true,
  trimCustomFragments: true,
  useShortDoctype: true,
}

export const minify = async () => {
  const file = await Deno.readTextFile('index.html')
  const content = await minifyHTML(file, minifyOpts)
  console.log(
    `index.html: ${toKB(content.length)}`,
    `(${toKB(file.length - content.length)} saved)`,
  )

  await Deno.mkdir('build', { recursive: true })
  return Deno.writeTextFile('build/index.html', content)
}
